name: Publish Github Pages
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v2

      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'

      - name: Install Dependencies
        run: yarn install

      - name: Build Pages
        run: yarn build

      - name: Publish generated content to GitHub Pages
        uses: tsunematsu21/actions-publish-gh-pages@v1.0.2
        with:
          dir: dist
          branch: gh-pages
          token: ${{ secrets.GITHUB_TOKEN }}